/**
 *  \file  libclipboard-config.h
 *  \brief Configuration specific options
 *
 *  \copyright Copyright (C) 2016 Jeremy Tan.
 *             This file is released under the MIT license.
 *             See LICENSE for details.
 *
 *  \details NOTE: This file is automatically generated.
 */

#ifndef _LIBCLIPBOARD_CONFIG_H
#define _LIBCLIPBOARD_CONFIG_H

/** Major version of libclipboard **/
#define LIBCLIPBOARD_VERSION_MAJOR 1

/** Minor version of libclipboard **/
#define LIBCLIPBOARD_VERSION_MINOR 0

/** Are we building the Win32 backend? **/
/* #undef LIBCLIPBOARD_BUILD_WIN32 */

/** Are we building the X11 backend? **/
/* #undef LIBCLIPBOARD_BUILD_X11 */

/** Are we building the Cocoa (OS X) backend? **/
/* #define LIBCLIPBOARD_BUILD_COCOA */

/** Are we building a shared library? **/
/* #undef LIBCLIPBOARD_BUILD_SHARED */

/** Are we using the stdcall calling convention? **/
/* #undef LIBCLIPBOARD_USE_STDCALL */

#endif /* _LIBCLIPBOARD_CONFIG_H */
